### PR TITLE
Feature ge refactoring and fixing problems

### LINKED ISSUE #100: Searching for doctors and patients
Searching for doctors, patients and specialists (https://github.com/PSW-2020-ORG9/HealthcareIS/pull/99#discussion_r548758712) through combobox is not practical. It is necessary to provide a search through some parameters.

### PR DESCRIPTION
**Pull request by denisfruza**
Hospital Map now has search tabs (equipment tab,medicine tab, appointment tab etc.) 
Function names in project are fixed.
When user needs to select patient or doctor, now he is able first to type name in text box and combo box is filtered by text box.
fix #100

### CODE REVIEW

File: HospitalWebApp/Controllers/DoctorController.cs [hunk 1]
```diff
@@ -30,25 +30,25 @@ public IActionResult GetBySpecialty(int specialtyId)
...
-            Doctor doctor = doctorService.GetByID(doctorId);
+            Doctor doctor = doctorService.GetByID(id);
             if (doctor != null) return Ok(doctor);
-            return BadRequest("Doctor with id: " + doctorId + " not found.");
+            return BadRequest("Doctor with id: " + id + " not found.");
         }
 
         [HttpGet]
-        [Route("getAllSpecialists")]
+        [Route("specialist")]
```
Comment (BoKna031) [inline HospitalWebApp/Controllers/DoctorController.cs:51]: maybe "specialists" is better Route

File: WPFHospitalEditor/Building.xaml [hunk 2]
```diff
@@ -7,11 +7,11 @@
...
         Title="Building" Height="650" Width="870" WindowStartupLocation="CenterScreen" ResizeMode="NoResize" Background="#FFC6F5F8">
     <StackPanel Orientation="Vertical">
-        <Canvas MinHeight="400" Margin="20,20,20,20" Background="LightGray" Name="canvas" MouseLeftButtonDown="selectMapObject"/>
+        <Canvas MinHeight="400" Margin="20,20,20,20" Background="LightGray" Name="canvas" MouseLeftButtonDown="SelectMapObject"/>
         <StackPanel Orientation="Horizontal">
-            <Button Background="#BDE7D8" Height="30" Width="100" Name="back" Content="Back" Margin="20,0,20,30" HorizontalAlignment="Left" Click="back_Click"/>
+            <Button Background="#BDE7D8" Height="30" Width="100" Name="back" Content="Back" Margin="20,0,20,30" HorizontalAlignment="Left" Click="Back_Click"/>
             <TextBlock FontSize="16">Change floor:</TextBlock>
-            <ComboBox x:Name="floor" Width="154" Height="30" Margin="10,-30,0,0" SelectionChanged="floor_SelectionChanged">
+            <ComboBox x:Name="floor" Width="154" Height="30" Margin="10,-30,0,0" SelectionChanged="Floor_SelectionChanged">
```
Comment (BoKna031) [inline WPFHospitalEditor/Building.xaml:14]: Some methods have "_" in their name and some do not. But I don't see the logic when you should use one before the other.

File: WPFHospitalEditor/Controller/DoctorServerController.cs [hunk 3]
```diff
@@ -20,9 +20,19 @@ public Doctor GetDoctorById(int doctorId)
             return doctorServerService.GetDoctorById(doctorId);
         }
 
+        public IEnumerable<DoctorDto> GetFilteredDoctors(string name)
+        {
+            return doctorServerService.GetFilteredDoctors(name);
+        }
+
```
Comment (BoKna031) [inline WPFHospitalEditor/Controller/DoctorServerController.cs:27]: Name FilteredDoctor is confusing. It's better name it something like SearchDoctors

File: WPFHospitalEditor/Controller/DoctorServerController.cs [hunk 4]
```diff
@@ -20,9 +20,19 @@ public Doctor GetDoctorById(int doctorId)
...
         public IEnumerable<DoctorDto> GetAllSpecialists()
         {
             return doctorServerService.GetAllSpecialists();
         }
+
+        public IEnumerable<DoctorDto> GetFilteredSpecialists(string name)
+        {
+            return doctorServerService.GetFilteredSpecialists(name);
+        }
```
Comment (BoKna031) [inline WPFHospitalEditor/Controller/DoctorServerController.cs:36]: Same problem as above

File: WPFHospitalEditor/Controller/EquipmentTypeServerController.cs [hunk 5]
```diff
@@ -14,5 +14,10 @@ public IEnumerable<EquipmentTypeDto> GetAllEquipmentTypes()
         {
             return EquipmentTypeServerService.GetAllEquipmentTypes();
         }
+
+        public IEnumerable<EquipmentTypeDto> GetFilteredEquipmentTypes(string name)
+        {
+            return EquipmentTypeServerService.GetFilteredEquipmentTypes(name);
```
Comment (BoKna031) [inline WPFHospitalEditor/Controller/EquipmentTypeServerController.cs:20]:
```suggestion
        public IEnumerable<EquipmentTypeDto> SearchEquipmentTypes(string name)
        {
            return EquipmentTypeServerService.SearchEquipmentTypes(name);
```

File: WPFHospitalEditor/Controller/MapObjectController.cs [hunk 6]
```diff
@@ -9,25 +9,25 @@ public class MapObjectController : IMapObjectController
...
         {
-            return IMapObjectService.getOutterMapObjects();
+            return IMapObjectService.GetOutterMapObjects();
         }
-        public MapObject findMapObjectById(int id)
+        public MapObject FindMapObjectById(int id)
         {
-            return IMapObjectService.findMapObjectById(id);
+            return IMapObjectService.FindMapObjectById(id);
         }
```
Comment (BoKna031) [inline WPFHospitalEditor/Controller/MapObjectController.cs:27]: You introduce a new category of method (Find). It would be better to use already existing categories of methods such as Get or Search

File: WPFHospitalEditor/Controller/MapObjectController.cs [hunk 7]
```diff
@@ -9,25 +9,25 @@ public class MapObjectController : IMapObjectController
...
-        public List<MapObject> searchForMapObjects(string name, string type)
+        public List<MapObject> SearchForMapObjects(string name, string type)
```
Comment (BoKna031) [inline WPFHospitalEditor/Controller/MapObjectController.cs:28]: Maybe better name for method would be SearchMapObjects

File: WPFHospitalEditor/Controller/DoctorServerController.cs (hunk 4 above)
Comment (rammba) [reply WPFHospitalEditor/Controller/DoctorServerController.cs:36]: You also have "filter" in names for medication and patients.

File: WPFHospitalEditor/Controller/MapObjectController.cs [hunk 8]
```diff
@@ -9,25 +9,25 @@ public class MapObjectController : IMapObjectController
...
         {
-            return IMapObjectService.searchForMapObjects(name, type);
+            return IMapObjectService.SearchForMapObjects(name, type);
```
Comment (BoKna031) [inline WPFHospitalEditor/Controller/MapObjectController.cs:30]: Maybe better name for method would be SearchMapObjects

File: WPFHospitalEditor/ScheduleWindow.xaml.cs [hunk 9]
```diff
@@ -24,25 +23,23 @@ public ScheduleWindow(RecommendationDto recommendationDto)
         {
             InitializeComponent();
             this.recommendationDto = recommendationDto;
-            setAppointmentInfoContent();
-            allPatients = patientServerController.GetAllPatients().ToList();
-            foreach (Patient p in allPatients)
-                patients.Items.Add(p.Id.ToString() + " " + p.Person.Name + " " + p.Person.Surname + " - " + p.Person.Jmbg);
+            SetAppointmentInfoContent();
+            SetPatientNameNameComboBox();
```
Comment (rammba) [inline WPFHospitalEditor/ScheduleWindow.xaml.cs:27]: I'm not sure which value textbox has by default, but it can be empty string, so you will pull all patients on start. Maybe it's better to call setPatientNameCombo method only on textbox changing.

File: WPFHospitalEditor/ScheduleWindow.xaml.cs [hunk 10]
```diff
@@ -57,7 +54,23 @@ private void scheduleBtn_Click(object sender, RoutedEventArgs e)
...
+            patientsComboBox.SelectedIndex = 0;
+            SetPatientNameNameComboBox();
+        }
+
+        private void SetPatientNameNameComboBox()
+        {
+            foreach (Patient p in patientServerController.GetFilteredPatients(PatientSearchInput.Text))
+            {
+                patientsComboBox.Items.Add(p.Id.ToString() + " " + p.Person.Name + " " + p.Person.Surname + " - " + p.Person.Jmbg);
+            }
```
Comment (rammba) [inline WPFHospitalEditor/ScheduleWindow.xaml.cs:70]: You should add "None" option here and select index 0. Also you should change name of method to SetPatientNameComboBox.

File: WPFHospitalEditor/ScheduleWindow.xaml.cs [hunk 11]
```diff
@@ -24,25 +23,23 @@ public ScheduleWindow(RecommendationDto recommendationDto)
...
         {
-            if (patients.SelectedIndex == -1)
+            if (patientsComboBox.SelectedIndex == -1)
             {
                 MessageBox.Show("You must select a patient!");
             }
             else { 
-                String patient = patients.SelectedItem.ToString();
+                String patient = patientsComboBox.SelectedItem.ToString();
                 int patientID = int.Parse(patient.Split(" ")[0]);
```
Comment (rammba) [inline WPFHospitalEditor/ScheduleWindow.xaml.cs:43]: If I understand right, you need to check if selected index is 0, because with new changes that is selected by default.

File: WPFHospitalEditor/HospitalMap.xaml.cs [hunk 12]
```diff
@@ -28,47 +29,56 @@ public partial class HospitalMap : Window
...
-            setDoctorNameComboBox();
-            setNonSelectedComboBoxItem();
-            CanvasService.addObjectToCanvas(mapObjectController.getOutterMapObjects(), canvas);
+            SetMapObjectTypeComboBox();
+            SetEquipmentTypeComboBox();
+            SetMedicationNameComboBox();
+            SetDoctorNameComboBox();
+            SetSpecialistNameComboBox();
+            SetSpecialistEquipmentComboBox();
+            SetNonSelectedComboBoxItem();
```
Comment (BoKna031) [inline WPFHospitalEditor/HospitalMap.xaml.cs:48]: You get all values for different combobox type in beginning, also every time you change search value in specific tab you will call it again. Problem with that is that you will communicate with repositories more often then you should do. That slows application. Also, you will get values for combobox which you probably won't use. Better way to solve this problem is to call specific function for setting combobox values only when you access tab that contains that combobox. Then  when you want to filter you could get all values **from combobox** and filter so they match searching parameters.

File: HospitalWebApp/Controllers/DoctorController.cs (hunk 1 above)
Comment (dbulaja98) [reply HospitalWebApp/Controllers/DoctorController.cs:51]: Yes, I agree, its fixed.

File: WPFHospitalEditor/Building.xaml (hunk 2 above)
Comment (dbulaja98) [reply WPFHospitalEditor/Building.xaml:14]: Fixed.

File: WPFHospitalEditor/Controller/DoctorServerController.cs (hunk 4 above)
Comment (dbulaja98) [reply WPFHospitalEditor/Controller/DoctorServerController.cs:36]: I renamed all of them.

File: WPFHospitalEditor/Controller/MapObjectController.cs (hunk 8 above)
Comment (dbulaja98) [reply WPFHospitalEditor/Controller/MapObjectController.cs:30]: Renamed.

File: WPFHospitalEditor/Controller/MapObjectController.cs (hunk 6 above)
Comment (dbulaja98) [reply WPFHospitalEditor/Controller/MapObjectController.cs:27]: Renamed.

File: WPFHospitalEditor/ScheduleWindow.xaml.cs (hunk 9 above)
Comment (dbulaja98) [reply WPFHospitalEditor/ScheduleWindow.xaml.cs:27]: I am not sure if I understood this comment properly. If I did, user doesn't need to write something in textbox, he can just choose from the combobox, and at the beginning there must be a full list of patients in the combobox. Also, now I see name of method, it was accident, it is fixed now.

File: WPFHospitalEditor/ScheduleWindow.xaml.cs (hunk 10 above)
Comment (dbulaja98) [reply WPFHospitalEditor/ScheduleWindow.xaml.cs:70]: You are right, I have fixed it.

File: WPFHospitalEditor/ScheduleWindow.xaml.cs (hunk 11 above)
Comment (dbulaja98) [reply WPFHospitalEditor/ScheduleWindow.xaml.cs:43]: Because of changes from the last comment, now index 0 is "None".

File: WPFHospitalEditor/ScheduleWindow.xaml.cs (hunk 9 above)
Comment (rammba) [reply WPFHospitalEditor/ScheduleWindow.xaml.cs:27]: If the idea is that user can choose from combo on beginning, that's ok then.

File: WPFHospitalEditor/HospitalMap.xaml.cs (hunk 12 above)
Comment (rammba) [reply WPFHospitalEditor/HospitalMap.xaml.cs:48]: I think that these methods will be called two times on program start. First time from text changed method in initialization, and second time here. You should check that.

Comment (dbulaja98) [reply WPFHospitalEditor/HospitalMap.xaml.cs:48]: Fixed. Now comboboxes are filled when specific tab is selected.

**Review by BoKna031 — APPROVED** [review]

**Comment by rammba** [comment]
[(1)PR Feature ge refactoring and fixing problems](https://trello.com/c/MQYkfEd0/122-1pr-feature-ge-refactoring-and-fixing-problems)

**Review by rammba — APPROVED** [review]
